### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by dlbus4-5076** [Hiyoteam/ChatroomHistoryBook#13]
我现在有github号了。
-----------------建议
 2022年8月26日，QiuLingYan在视频的评论中侮辱了B站的J，甚至没过几天便重新获得管理。B站的J向QiuLingYan质问该年8月16日发生的JSPVZ事件，QiuLingYan却逃避问题，还嘲讽“B站的J只有4年级”。

明明QiuLingYan也是小学生uwu ——ee

 B站的J、snose两人与QiuLingYan展开骂战，QiuLingYan将两人禁言。后MelonFish介入本事件，B站的J和snose发现XC管理QiuLingYan滥用权限，将历史记录中自己发言的部分删掉，且将XC聊天室?jspvz频道的记录彻底删除，试图掩盖证据。XC名声在JSPVZ进一步恶化。

 本节内容转载并修改自当时的JSPVZ社区Wiki。
------------------------
此段内容与前面重复且有错误，应当删除。

**Comment by 0x24a** [comment]
请提交Pull request,而不是Issue.
