### ISSUE TITLE
关于大家对我视频的理解

### ISSUE THREAD

**Issue by dlbus4-5076** [Hiyoteam/ChatroomHistoryBook#14]
第二天，B站的J在B站发了关于声讨XC管理的[视频](https://www.bilibili.com/video/BV1Te4y1f7zg/)，就IP泄露问题向XC讨要说法。MelonFish在视频中做出了解释，但目前此视频已被B站的J删除。以下是MelonFish在评论中的原话（由ee添加了换行）。

我声明一下，我发这个视频是为了叙述这个事件，而不是声讨XC。故此段内容应改为：

第二天，B站的J在B站发了关于本次事件的视频。MelonFish在视频中做出了解释，但目前此视频已被B站的J删除。以下是MelonFish在评论中的原话（由ee添加了换行）。

**Comment by 0x24a** [comment]
欢迎提交Pull request而不是Issue.
